# Generated by Django 2.2.4 on 2019-08-09 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Health', 'health'), ('Education', 'edu'), ('Sports', 'sports'), ('Politics', 'politics')], default='Education', max_length=40)),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('editor', models.CharField(max_length=80)),
            ],
        ),
    ]
