# Generated by Django 2.2.4 on 2019-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to='profile_pics', verbose_name='content'),
        ),
    ]
